### PR TITLE
[feature] fetch cancellation data

### PR DESCRIPTION
**Pull request by damianmamlachargify**
This endpoint `'subscriptions/:subscription_id/cancellation_data'` is needed to enable scheduling subscription cancellation in the billing portal

Reference: https://github.com/chargify/chargify/pull/17514/files

### CODE REVIEW

**Comment by wsmoak** [comment]
Do we have other endpoints with 'data' in the name?  (Was that chosen for a reason?)  Could it be subscriptions/123/cancellations ? (with filters if needed)

**Comment by wsmoak** [comment]
Do we have other endpoints with 'data' in the name?  (Was that chosen for a reason?)  Could it be subscriptions/123/cancellations ? (with filters if needed)

**Comment by damianmamlachargify** [comment]
> Do we have other endpoints with 'data' in the name? (Was that chosen for a reason?) Could it be subscriptions/123/cancellations ? (with filters if needed)

This endpoint is returning data that I need to display a new cancellation page. This data looks like this:
``` 
{
                 "subscription" => {
                                  "id" => 17,
                               "state" => "Active",
        "formattedCurrentPeriodEndsAt" => "12/30/2020 09:48AM EST",
                  "linkToSubscription" => "/subscriptions/17"
    },
                  "reasonCodes" => [
        {
                     "id" => "19",
                   "code" => "AAA",
            "description" => "Mollitia soluta vel cumque qui sed quod."
        },
         {
                     "id" => "21",
                   "code" => "BBB",
            "description" => "Aut ipsa est sint eum qui repudiandae reprehenderit esse."
        }
    ],
    "reasonCodesSettingPageUrl" => "/settings#reason-codes",
                 "endOfPeriods" => [
         {
            "label" => "December 30, 2020",
            "value" => "2020-12-30T09:48:21-05:00"
        },
        {
            "label" => "January 30, 2021",
            "value" => "2021-01-30T09:48:21-05:00"
        },
         {
            "label" => "February 28, 2021",
            "value" => "2021-02-28T09:48:21-05:00"
        },
        {
            "label" => "March 28, 2021",
            "value" => "2021-03-28T10:48:21-04:00"
        },
        {
            "label" => "April 28, 2021",
            "value" => "2021-04-28T10:48:21-04:00"
        },
         {
            "label" => "May 28, 2021",
            "value" => "2021-05-28T10:48:21-04:00"
        }
    ]
}

```
If I would name it like this `subscriptions/123/cancellations` somebody for sure would expect that this endpoint will return `cancellations` records for a specific subscription. And as you can see this endpoint has nothing to do with the `cancellations`.

**Review by nschimka — APPROVED** [review]
🚢  Sounds reasonable to me

**Pull request merged**
